[package]
name = "randchaind"
version = "0.0.1"
license = "GPL-3.0"
authors = [Haoyu Lin <chris.haoyul@gmail.com>"]
description = "RandChain client."

[profile.dev]
debug = true
panic = 'abort'

[profile.release]
debug = true
panic = 'abort'

[profile.test]
debug = true

[[bin]]
path = "randchaind/main.rs"
name = "randchaind"
