[package]
name = "network"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
rug = "1.3.0"
ecvrf = "0.4.2"
chain = { path = "../chain" }
primitives = { path = "../primitives" }
