[package]
name = "network"
version = "0.1.0"
authors = [ "debris <marek.kotewicz@gmail.com>" ]

[dependencies]
chain = { path = "../chain" }
lazy_static = "1.4.0"
primitives = { path = "../primitives" }
rug = "1.3.0"
bitcrypto = { path = "../crypto" }