[package]
name = "serialization_derive"
version = "0.1.0"
authors = [ "debris <marek.kotewicz@gmail.com>" ]

[lib]
name = "serialization_derive"
proc-macro = true

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[dev-dependencies]
serialization = { path = "../serialization" }
