# `docker-compose up --scale node=4`
version: '3'
services:
  seednode:
    domainname: "dnsseed.randchain.org"
    tty: true
    image: randchain-dev/dnsseeder:latest
    entrypoint: /dnsseeder/dnsseeder
    command: ["-v", "-netfile", "/dnsseeder/configs/randchain.json"]
    cap_add:
      - ALL
    extra_hosts: 
      - "dnsseed.randchain.org:10.0.0.200"
    restart: always
    networks:
      randchain_privnet:
        ipv4_address: 10.0.0.200

  node:
    tty: true
    image: randchain-dev/randchain:latest
    entrypoint: /bin/randchain
    command: ["-s", "dnsseed.randchain.org", "-p", "10.0.0.2:8333,10.0.0.3:8333"]
    dns:
      - 10.0.0.200
    cap_add:
      - ALL
    environment:
      - RUST_BACKTRACE=full
      - RUST_LOG=trace
    depends_on: 
      - seednode
    networks:
      - randchain_privnet

networks:
  randchain_privnet:
    driver: macvlan
    ipam:
      config:
        - subnet: 10.0.0.0/8