[package]
name = "bitcrypto"
version = "0.1.0"
authors = [ "debris <marek.kotewicz@gmail.com>" ]

[dependencies]
primitives = { path = "../primitives" }
rust-crypto = "0.2.36"
siphasher = "0.1.1"

rand = "0.7"
rand_core = "0.5.1"
sha3 = "0.9.1"
curve25519-dalek = "3.1.0"
