name: Build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: cargo clippy
      - uses: actions/checkout@v2
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
